Python practice 2

In [4]:
#dictionaries
#key value pair mappings

d = {'key1': 'value', 'key2': 123}

In [6]:
d['key2']


123

In [8]:
d = {'L1':[1,2,3]}

In [11]:
d['L1'][0]

1

In [12]:
d = {'k1':{'innerkey':[1,2,3]}}

In [14]:
d['k1']['innerkey'][1]

2

In [17]:
#list is a seq of charac separated by commas in sq prac
#tuple is the same thing but uses paranthesis ()
#difference tuples are immutable

t = (1,2,3)
t[0]

1

In [18]:
t


(1, 2, 3)

In [20]:
{1,2,3,4,5,6,6,6,6}

{1, 2, 3, 4, 5, 6}

In [21]:
set([1,1,1,1,2,4,4,5])

{1, 2, 4, 5}

In [22]:
s = {1,2,3}
s.add(5)

In [23]:
s

{1, 2, 3, 5}

In [24]:
1 > 8

False

In [25]:
8 < 8


False

In [26]:
1 < 2

True

In [27]:
1 << 2

4

In [28]:
2 >> 4

0

In [30]:
2 == 3

False

In [31]:
2!=3

True

In [32]:
"hi" == "HI"

False

In [36]:
"hi" == "hi"

True

In [37]:
True or False

True

In [38]:
True and False


False

In [39]:
False and False

False

In [6]:
x = [1,2,3,4,5]
for i in x:
    print(i)

1
2
3
4
5


In [5]:
i = 1
while i <= 5:
    print('i is {}'.format(i))
    i+=1
    

i is 1
i is 2
i is 3
i is 4
i is 5


In [7]:
range(1,10)

range(1, 10)

In [8]:
for x in range(0,5):
    print(x)

0
1
2
3
4


In [9]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
x = [1,2,3,4]

In [20]:
out = []

In [12]:
for num in x:
    out.append(num**2)

In [13]:
out

[1, 4, 9, 16]

In [25]:
out=[num**2 for num in x]

In [26]:
out

[1, 4, 9, 16]

In [27]:
def my_func(param1):
    print(param1)

In [28]:
my_func('hello')

hello


In [29]:
 def times2(var):
        return var*2
    

In [30]:
times2(5)

10

In [31]:
#map
seq = [1,2,3,4,5]

In [38]:
map(times2,seq)

In [43]:
seq
#list will map it to every item in the list

[1, 2, 3, 4, 5]

In [42]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [44]:
#lambda expressions

In [46]:
lambda var:var*2

<function __main__.<lambda>(var)>

In [47]:
t = lambda var:var*2

In [50]:
list(map(lambda num : num*2,seq))

[2, 4, 6, 8, 10]

In [52]:
list(filter(lambda num: num%2==0,seq))

[2, 4]

#returns only the even nums, the nums that satisfy the filter condition, true ones are returned

In [54]:
s = 'hello my name is Navi'

In [55]:
s.lower()

'hello my name is navi'

In [56]:
s.upper()

'HELLO MY NAME IS NAVI'

In [59]:
s.split()

['hello', 'my', 'name', 'is', 'Navi']

In [61]:
s.split('name')

['hello my ', ' is Navi']

In [62]:
s.split('name')[1]

' is Navi'

In [63]:
d = {'k1': 1, 'k2':2 }
d.keys()

dict_keys(['k1', 'k2'])

In [64]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [65]:
d.values()

dict_values([1, 2])

In [82]:
l2 = [1,2,3]

In [86]:
l2.pop()

IndexError: pop from empty list

In [78]:
l2

[]

In [93]:
list1 = [1,2,3,4,5] 
Lr=[]
for i in range(len(list1)):
     Lr.append((list1.pop()))
print(Lr)

[5, 4, 3, 2, 1]


In [94]:
Lr.pop(0)

5

In [95]:
Lr

[4, 3, 2, 1]

In [97]:
'5' in [1,2,5]

False

In [98]:
#tuple unpacking

In [101]:
x = [(1,2),(3,4),(5,6)]


In [102]:
x[0][1]

2

In [103]:
for item in x:
    print(item)

(1, 2)
(3, 4)
(5, 6)


In [105]:
for item,item2 in x:
    print(item)

1
3
5


In [106]:
7**4

2401

In [107]:
print(list(s.split()))

['hello', 'my', 'name', 'is', 'Navi']


In [109]:
s.split()

['hello', 'my', 'name', 'is', 'Navi']

In [110]:
planet = "earth"
diameter = 12332

In [114]:
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of earth is 12332 kilometers


In [116]:
#lst[3][1][2][0]

In [117]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [118]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [126]:
def domainGet(name):
    return name.split('@')[1]

In [127]:
domainGet('navi@gmail.com')

'gmail.com'

In [136]:
def findDog(line):
    return 'dog' in line.lower().split()

In [138]:
findDog('IS there a bo Dog here')

True

In [139]:
def countDog(line2):
    count = 0
    for word in line2.lower().split():
        if word == 'dog':
            count+=1
    return count
        
    
    

In [140]:
countDog('i got the dog dog DOG in me')

3

In [146]:
seq = ['salt','sea','lion']

In [147]:
list(filter(lambda s: s[0]=='s',seq))

['salt', 'sea']

In [148]:
#numpy

In [149]:
import numpy as np


In [150]:
my_list = [1,2,3]

In [151]:
np.array(my_list)

array([1, 2, 3])

In [152]:
arr = np.array(my_list)

In [153]:
arr

array([1, 2, 3])

In [154]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [155]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
np.zeros(3)

array([0., 0., 0.])

In [158]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [159]:
np.ones(4)

array([1., 1., 1., 1.])

In [163]:
np.linspace(0,5,10)
#get evenly spaced points between two numbers
#its one dimensional

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [165]:
#identity matrix
np.eye(4)
#2d square matrix diagnols of 1s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [168]:
np.random.rand(5)
#unif distri number between 0 to 1

array([0.18069118, 0.8876558 , 0.1805073 , 0.65553725, 0.92129911])

In [169]:
np.random.rand(5,5)

array([[0.97417412, 0.6529182 , 0.66513272, 0.19107618, 0.46581294],
       [0.20774201, 0.97424589, 0.02356903, 0.1966149 , 0.96595094],
       [0.17989291, 0.35408724, 0.24298198, 0.15710899, 0.23727142],
       [0.49898938, 0.25983424, 0.42918841, 0.50866193, 0.0461255 ],
       [0.49696211, 0.72299818, 0.23056971, 0.77620015, 0.5056203 ]])

In [173]:
np.random.randn(2,2)
#standard normal distribution

array([[-0.02343109,  0.03432524],
       [-1.34530112, -0.48478441]])

In [174]:
np.random.randint(1,100)

41

In [175]:
#low inclusive high not inc

In [176]:
np.random.randint(1,100,10)

array([38, 81, 23, 27, 81, 13, 37, 98, 65, 71])

In [178]:
arr = np.arange(25)

In [179]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [180]:
ranarr= np.random.randint(0,50,10)

In [181]:
ranarr

array([ 7,  0, 47, 14, 35, 36, 11, 36, 34, 26])

In [183]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [184]:
ranarr

array([ 7,  0, 47, 14, 35, 36, 11, 36, 34, 26])

In [185]:
ranarr.argmin()

1

In [186]:
#returns location

In [187]:
arr.shape

(25,)

In [189]:
arr.dtype

dtype('int64')

In [190]:
from numpy.random import randint

In [191]:
randint(2,10)

8

In [195]:
arr = np.arange(0,11)

In [196]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [197]:
arr[8]

8

In [198]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [199]:
arr[1:5]

array([1, 2, 3, 4])

In [200]:
 arr[:6]

array([0, 1, 2, 3, 4, 5])

In [201]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [202]:
arr[0:5]=100

In [203]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [204]:
arr_copy = arr.copy()

#this is to create copy to change values without affecting the original array

In [206]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [207]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [208]:
arr_2d[0][0]

5

In [209]:
arr_2d[0]

array([ 5, 10, 15])

In [210]:
arr_2d[0,0]

5

In [212]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [213]:
arr = np.arange(1,11)

In [214]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [218]:
bool_arr=arr > 5

In [219]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [220]:
arr[arr<3]

array([1, 2])

In [221]:
arr_2d = np.arange(50).reshape(5,10)

In [222]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [224]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [230]:
arr = np.arange(0,10)

In [231]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [233]:
arr.reshape

<function ndarray.reshape>

In [236]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [237]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [249]:
x = (arr * arr).reshape(2,5)

In [243]:
arr.reshape(2,5) + arr.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [250]:
x*x

array([[   0,    1,   16,   81,  256],
       [ 625, 1296, 2401, 4096, 6561]])

In [251]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [255]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [258]:
y = arr ** 2

In [257]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [259]:
y.max()

81

In [1]:
 import numpy as np

Create an array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
a = np.arange(9)

In [14]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.rand(1)

array([0.85651416])

In [17]:
np.random.randn(25)

array([-1.59516552,  0.67575155, -2.31262328,  1.56063965, -2.21958338,
        1.1487418 ,  0.35658414,  0.5590954 ,  0.50607798,  0.21625496,
       -1.09515408,  0.99038672,  0.03155421, -0.58039496, -0.37381271,
       -2.16179362,  0.3660354 , -0.17316886, -1.14813577, -1.06618162,
       -0.31976073, -1.62261294, -2.07847951,  0.25976325, -0.33648009])

In [22]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [23]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [25]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [26]:
mat = np.arange(1,26).reshape(5,5)

In [27]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
mat[3][4]

20

In [34]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [36]:
mat[4:,0:] //or use negative indexing ie -1

array([[21, 22, 23, 24, 25]])

In [37]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [38]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
np.sum(mat)

325

above is the code to get the sum of all values in the matrix

In [40]:
mat.sum()

325

In [41]:
mat.sum

<function ndarray.sum>

In [42]:
np.std(mat)

7.211102550927978

In [43]:
mat.std()

7.211102550927978

In [44]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Pandas

Series

similar to numpy array built on top of nparr obj

In [56]:
import pandas as pd

In [57]:
labels = ['a','b','c']
my_data = [10,20,30]

In [58]:
arr = np.array(my_data)
d = {'a':10 , 'b':20, 'c':30}

In [60]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [61]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [62]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [63]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [65]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [67]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [68]:
#can hold a variety of object types

In [70]:
pd.Series(labels,labels)

a    a
b    b
c    c
dtype: object

In [71]:
#using series and its index

In [73]:
#works like a hash table/dicy

In [75]:
s1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])

In [76]:
s1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [77]:
s2 = pd.Series([1,2,5,4],['USA','Germany','Italy','Japan'])

In [78]:
s2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [79]:
s1['USA']

1

In [80]:
s3= pd.Series(data = labels)

In [81]:
s3

0    a
1    b
2    c
dtype: object

In [82]:
s3[0]

'a'

In [83]:
s1+s2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

dataframes

In [84]:
from numpy.random import randn

In [87]:
np.random.seed(101)

In [91]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [92]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

dataframes is a bunch of series that shares an index

In [97]:
df['W']#better to use

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [98]:
type(df['W'])

pandas.core.series.Series

In [99]:
type(df)

pandas.core.frame.DataFrame

In [101]:
df.W #sql like format may get confused w the methods available for df

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [102]:
df[['W','Z']]

W         Z
A -0.993263  0.000366
B  1.025984  0.649826
C  2.154846 -0.346419
D  0.147027  1.024810
E -0.925874  0.610478

In [104]:
df['new'] = df['W']+df['Y']

In [105]:
df

W         X         Y         Z       new
A -0.993263  0.196800 -1.136645  0.000366 -2.129908
B  1.025984 -0.156598 -0.031579  0.649826  0.994405
C  2.154846 -0.610259 -0.755325 -0.346419  1.399521
D  0.147027 -0.479448  0.558769  1.024810  0.705796
E -0.925874  1.862864 -1.133817  0.610478 -2.059691

In [109]:
df.drop('A')

W         X         Y         Z       new
B  1.025984 -0.156598 -0.031579  0.649826  0.994405
C  2.154846 -0.610259 -0.755325 -0.346419  1.399521
D  0.147027 -0.479448  0.558769  1.024810  0.705796
E -0.925874  1.862864 -1.133817  0.610478 -2.059691

In [113]:
df.drop('new',axis =1,inplace = True)

In [112]:
#doesnt happen in place

In [114]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [116]:
#rows is 0 and colums is 1 and pd is built on top of Numpy

In [123]:
df.loc['A'] #loc stands for location

W   -0.993263
X    0.196800
Y   -1.136645
Z    0.000366
Name: A, dtype: float64

In [128]:
df.iloc[0] #index based loc based on num

W   -0.993263
X    0.196800
Y   -1.136645
Z    0.000366
Name: A, dtype: float64

In [129]:
df.loc['B','Y']

-0.031579143908112575

In [131]:
df.loc['A':'B','W':'Y']

W         X         Y
A -0.993263  0.196800 -1.136645
B  1.025984 -0.156598 -0.031579

In [133]:
df.loc[['A','B'],['W','Y']]

W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579

In [134]:
df > 0

W      X      Y      Z
A  False   True  False   True
B   True  False  False   True
C   True  False  False  False
D   True  False   True   True
E  False   True  False   True

In [135]:
booldf = df>0

In [136]:
booldf

W      X      Y      Z
A  False   True  False   True
B   True  False  False   True
C   True  False  False  False
D   True  False   True   True
E  False   True  False   True

In [137]:
df[booldf]

W         X         Y         Z
A       NaN  0.196800       NaN  0.000366
B  1.025984       NaN       NaN  0.649826
C  2.154846       NaN       NaN       NaN
D  0.147027       NaN  0.558769  1.024810
E       NaN  1.862864       NaN  0.610478

In [138]:
df[df>0]

W         X         Y         Z
A       NaN  0.196800       NaN  0.000366
B  1.025984       NaN       NaN  0.649826
C  2.154846       NaN       NaN       NaN
D  0.147027       NaN  0.558769  1.024810
E       NaN  1.862864       NaN  0.610478

In [139]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [140]:
df['W']>0

A    False
B     True
C     True
D     True
E    False
Name: W, dtype: bool

In [141]:
df['W']

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [142]:
df[df['W']>0]

W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [143]:
df[df['Z']<0]

W         X         Y         Z
C  2.154846 -0.610259 -0.755325 -0.346419

In [149]:
resultdf = df[df['W']>0]['X'] #can easily stack commands to return the x column

In [151]:
resultdf # get the same op in one step

B   -0.156598
C   -0.610259
D   -0.479448
Name: X, dtype: float64

In [155]:
df[df['W']>0][['Y','X']]

Y         X
B -0.031579 -0.156598
C -0.755325 -0.610259
D  0.558769 -0.479448

In [160]:
boolser = df['W']>0

SyntaxError: invalid syntax (3020583413.py, line 1)

In [157]:
result = df[boolser]

In [158]:
result

W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [159]:
boolser

A    False
B     True
C     True
D     True
E    False
Name: W, dtype: bool

In [161]:
result[['Y','X']]

Y         X
B -0.031579 -0.156598
C -0.755325 -0.610259
D  0.558769 -0.479448

In [165]:
df[(df['W']>0)&(df['Z']>1)]

W         X         Y        Z
D  0.147027 -0.479448  0.558769  1.02481

In [171]:
df.reset_index()

level_0 index         W         X         Y         Z
0        0     A -0.993263  0.196800 -1.136645  0.000366
1        1     B  1.025984 -0.156598 -0.031579  0.649826
2        2     C  2.154846 -0.610259 -0.755325 -0.346419
3        3     D  0.147027 -0.479448  0.558769  1.024810
4        4     E -0.925874  1.862864 -1.133817  0.610478

In [172]:
df

index         W         X         Y         Z
0     A -0.993263  0.196800 -1.136645  0.000366
1     B  1.025984 -0.156598 -0.031579  0.649826
2     C  2.154846 -0.610259 -0.755325 -0.346419
3     D  0.147027 -0.479448  0.558769  1.024810
4     E -0.925874  1.862864 -1.133817  0.610478

In [173]:
newind = 'CA NY WY OR CO'.split()

In [174]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [175]:
df['states'] = newind

In [176]:
df

index         W         X         Y         Z states
0     A -0.993263  0.196800 -1.136645  0.000366     CA
1     B  1.025984 -0.156598 -0.031579  0.649826     NY
2     C  2.154846 -0.610259 -0.755325 -0.346419     WY
3     D  0.147027 -0.479448  0.558769  1.024810     OR
4     E -0.925874  1.862864 -1.133817  0.610478     CO

In [177]:
df.set_index('states')

index         W         X         Y         Z
states                                              
CA         A -0.993263  0.196800 -1.136645  0.000366
NY         B  1.025984 -0.156598 -0.031579  0.649826
WY         C  2.154846 -0.610259 -0.755325 -0.346419
OR         D  0.147027 -0.479448  0.558769  1.024810
CO         E -0.925874  1.862864 -1.133817  0.610478

In [178]:
#index levels

In [195]:
outside = ['G1', 'G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [196]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [198]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [199]:
df

A         B
G1 1 -1.382920  1.482495
   2  0.961458 -2.141212
   3  0.992573  1.192241
G2 1 -1.046780  1.292765
   2 -1.467514 -0.494095
   3 -0.162535  0.485809

In [200]:
df.loc['G1']

A         B
1 -1.382920  1.482495
2  0.961458 -2.141212
3  0.992573  1.192241

In [204]:
df.loc['G1'].loc[1]

A   -1.382920
B    1.482495
Name: 1, dtype: float64

In [206]:
df.index.names = ['Groups', 'Num']

In [207]:
df

A         B
Groups Num                    
G1     1   -1.382920  1.482495
       2    0.961458 -2.141212
       3    0.992573  1.192241
G2     1   -1.046780  1.292765
       2   -1.467514 -0.494095
       3   -0.162535  0.485809

In [213]:
df.loc['G2'].loc[2]['B']

-0.49409535833912277

In [215]:
df.loc['G1']

A         B
Num                    
1   -1.382920  1.482495
2    0.961458 -2.141212
3    0.992573  1.192241

In [217]:
df.xs('G1') #used to get cross section sub section in multi level index

A         B
Num                    
1   -1.382920  1.482495
2    0.961458 -2.141212
3    0.992573  1.192241

In [219]:
df.xs(1,level='Num')

A         B
Groups                   
G1     -1.38292  1.482495
G2     -1.04678  1.292765

In [220]:
#Missing data

In [222]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [223]:
df = pd.DataFrame(d)

In [224]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [226]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [227]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [228]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [229]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [234]:
df.fillna(value = 'Fillval')

A        B  C
0      1.0      5.0  1
1      2.0  Fillval  2
2  Fillval  Fillval  3

In [235]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [236]:
#groupby

In [238]:

data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [239]:
df = pd.DataFrame(data)

In [240]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [249]:
byComp=df.groupby('Company')

In [250]:
byComp

In [251]:
byComp.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [252]:
byComp.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [255]:
x = byComp.sum().loc['FB']


In [256]:
x

Sales    593
Name: FB, dtype: int64

In [257]:
df.groupby('Company').sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [258]:
df.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [266]:
x = df.groupby('Company').max()

In [277]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [278]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [279]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [280]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [281]:
pd.concat([df1,df2,df3])


A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [282]:
pd.concat([df1,df2,df3],axis=1)


A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [285]:
left = pd.DataFrame({
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],'key': ['K0', 'K1', 'K2', 'K3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    


In [286]:
pd.merge(left,right,how='inner',on='key')

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [288]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})


In [289]:

df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [290]:
#3 main useful methods to find uniq vals in df

In [291]:
df['col2'].unique()

array([444, 555, 666])

In [292]:
#to check no of vals

In [293]:
len(df['col2'].unique())

3

In [294]:
# or

In [295]:
df['col2'].nunique()

3

In [296]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [297]:
#selecting data

In [299]:
df[df['col1']>2]

col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [300]:
df['col1']>2 #this command is essentially a boolean series

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

to combine conditions wrap in paranthese and then use and or or

In [301]:
newdf = df[(df['col1']>2) & (df['col2']==444)]


In [302]:
newdf

col1  col2 col3
3     4   444  xyz

In [303]:
def times2(x):
    return x*2

In [304]:
df['col1'].sum()

10

In [306]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [307]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [308]:
#apply is powerful w lambda expressions and can be used to apply custom func

In [309]:
df['col2'].apply(lambda x:x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [310]:
df.drop('col1',axis=1)

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [311]:
#inplace can also be used

In [312]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [314]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [315]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [316]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [317]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [318]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [319]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [320]:
df.pivot_table('D',['A','B'],['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [322]:
df.pivot_table(values = 'D',index = ['A','B'],columns =['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [323]:
#data input and output

In [324]:
pwd

'/Users/navi/Python Practice'

In [325]:
pd.read_csv('/Users/navi/Downloads/Refactored_Py_DS_ML_Bootcamp-master 3/03-Python-for-Data-Analysis-Pandas/example')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [349]:
df = pd.read_csv('/Users/navi/Downloads/Refactored_Py_DS_ML_Bootcamp-master 3/03-Python-for-Data-Analysis-Pandas/example')

In [327]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [328]:
df.to_csv('My_output')

In [329]:
pd.read_csv('My_output')

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [330]:
df.to_csv('My_output', index = False)

In [331]:
pd.read_csv('My_output')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [338]:
pd.read_excel("/Users/navi/Downloads/Refactored_Py_DS_ML_Bootcamp-master 3/03-Python-for-Data-Analysis-Pandas/Excel_Sample.xlsx",sheet_name= 'Sheet1')

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [339]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

In [342]:
data = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')

In [343]:
type(data)

list

In [344]:
data[0]

Bank NameBank       CityCity StateSt  CertCert  \
0             Heartland Tri-State Bank        Elkhart      KS     25851   
1                  First Republic Bank  San Francisco      CA     59017   
2                       Signature Bank       New York      NY     57053   
3                  Silicon Valley Bank    Santa Clara      CA     24735   
4                    Almena State Bank         Almena      KS     15426   
..                                 ...            ...     ...       ...   
562                 Superior Bank, FSB       Hinsdale      IL     32646   
563                Malta National Bank          Malta      OH      6629   
564    First Alliance Bank & Trust Co.     Manchester      NH     34264   
565  National State Bank of Metropolis     Metropolis      IL      3815   
566                   Bank of Honolulu       Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0                 Dream First Bank, N.A.       July 28, 2023     10544  
1              JPMorgan Chase Bank, N.A.         May 1, 2023     10543  
2                    Flagstar Bank, N.A.      March 12, 2023     10540  
3    First–Citizens Bank & Trust Company      March 10, 2023     10539  
4                            Equity Bank    October 23, 2020     10538  
..                                   ...                 ...       ...  
562                Superior Federal, FSB       July 27, 2001      6004  
563                    North Valley Bank         May 3, 2001      4648  
564  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
565              Banterra Bank of Marion   December 14, 2000      4646  
566                   Bank of the Orient    October 13, 2000      4645  

[567 rows x 7 columns]

In [345]:
data[0].head()

Bank NameBank       CityCity StateSt  CertCert  \
0  Heartland Tri-State Bank        Elkhart      KS     25851   
1       First Republic Bank  San Francisco      CA     59017   
2            Signature Bank       New York      NY     57053   
3       Silicon Valley Bank    Santa Clara      CA     24735   
4         Almena State Bank         Almena      KS     15426   

               Acquiring InstitutionAI Closing DateClosing  FundFund  
0               Dream First Bank, N.A.       July 28, 2023     10544  
1            JPMorgan Chase Bank, N.A.         May 1, 2023     10543  
2                  Flagstar Bank, N.A.      March 12, 2023     10540  
3  First–Citizens Bank & Trust Company      March 10, 2023     10539  
4                          Equity Bank    October 23, 2020     10538

In [346]:
from sqlalchemy import create_engine

In [347]:
engine = create_engine('sqlite:///memory')

In [350]:
df 

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [351]:
df.to_sql('my_table',engine)

4

In [352]:
sqldf= pd.read_sql('my_table', con = engine)

In [353]:
sqldf

index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15